![Logo de NumPy](https://github.com/4GeeksAcademy/machine-learning-prework/blob/main/02-numpy/assets/numpy_logo.png?raw=true)

## Introducción a NumPy

`NumPy` es un juego de palabras que significa **Python numérico** (*Numerical Python*). Es una librería de código abierto que se utiliza para llevar a cabo tareas matemáticas con altísima eficiencia. Además, introduce estructuras de datos como los arrays multidimensionales, que se pueden operar entre ellos a alto nivel, sin meterse mucho en el detalle.

En concreto, las claves de esta librería son:

- **Array multidimensionales**: Esta librería proporciona un objeto llamado `ndarray`, que permite almacenar y manipular grandes conjuntos de datos de forma eficiente. Los arrays pueden tener cualquier número de dimensiones.
- **Operaciones Vectorizadas**: NumPy permite realizar operaciones matemáticas en arrays completos sin la necesidad de bucles explícitos en el código, lo que lo hace muy rápido y eficiente.
- **Funciones matemáticas**: NumPy proporciona una amplia gama de funciones matemáticas para trabajar con arrays, incluyendo funciones trigonométricas, estadísticas, álgebra lineal, entre otras.
- **Eficiencia**: Es mucho más rápido que la misma funcionalidad implementada directamente sobre Python nativo. Además, es muy flexible en términos de acceso y manipulación de elementos individuales o subconjuntos de arrays.

NumPy es una biblioteca fundamental para el Machine Learning y la ciencia de los datos en Python. Proporciona una amplia gama de herramientas y funciones para trabajar eficientemente con datos numéricos en forma de arrays y matrices.

### Arrays

Un **array** de NumPy es una estructura de datos que permite almacenar una colección de elementos, generalmente números, en una o más dimensiones.

#### Array unidimensional

Un array unidimensional (1D) de NumPy es una estructura de datos que contiene una secuencia de elementos en una única dimensión. Es similar a una lista en Python, pero con las ventajas de rendimiento y funcionalidad que ofrece NumPy.

![Array de una dimensión](https://github.com/4GeeksAcademy/machine-learning-prework/blob/main/02-numpy/assets/1D.png?raw=true "1D")

Un array 1D puede ser creado usando la función `array` de la librería con una lista de elementos como argumento. Por ejemplo:

In [1]:
import numpy as np

array = np.array([1, 2, 3, 4, 5])
array

array([1, 2, 3, 4, 5])

Esto creará un array 1D con los elementos 1, 2, 3, 4 y 5. Los elementos del array deben ser del mismo tipo de datos. Si los elementos son de diferentes tipos, NumPy intentará convertirlos al mismo tipo si es posible.

En un array 1D, podemos acceder a los elementos usando **índices** (*indexes*), modificarlos y realizar operaciones matemáticas en el array completo de forma eficiente. A continuación se muestran algunas operaciones que se pueden realizar utilizando el array anterior:

In [2]:
# Acceder al tercer elemento
print(array[2])

# Cambiar el valor del segundo elemento
array[1] = 7
print(array)

# Sumar 10 a todos los elementos
array += 10
print(array)

# Calcular la suma de los elementos
sum_all = np.sum(array)
print(sum_all)

3
[1 7 3 4 5]
[11 17 13 14 15]
70


#### Array N-dimensional

Un array multidimensional o n-dimensional en NumPy es una estructura de datos que organiza elementos en múltiples dimensiones (ejes). Estos arrays permiten representar estructuras de datos más complejas, como matrices (array 2D, 2 ejes), tensores (array 3D, 3 ejes) y estructuras de mayor dimensión.

![Arrays de diferentes dimensiones](https://github.com/4GeeksAcademy/machine-learning-prework/blob/main/02-numpy/assets/3D.png?raw=true "3D")

Un array N-dimensional puede ser creado también usando la función `array` de la librería. Por ejemplo, si queremos crear un array 2D:

In [3]:
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Si ahora quisiéramos crear un array 3D, tendríamos que pensar en él como una lista de matrices:

In [4]:
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
array_3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

Al igual que sucedía con los arrays 1D, los elementos en un array multidimensional son accesibles mediante índices, se pueden realizar operaciones con ellos, etcétera.

A medida que agregamos más dimensiones, el principio básico sigue siendo el mismo: cada dimensión adicional puede considerarse como un nivel adicional de anidamiento. Sin embargo, a nivel práctico, trabajar con arrays de más de 3 o 4 dimensiones puede volverse más complejo y menos intuitivo.

Los arrays n-dimensionales en NumPy permiten una gran flexibilidad y potencia para representar y manipular datos en formas más complejas, especialmente útiles en campos como la ciencia de los datos, procesamiento de imágenes y aprendizaje profundo.

### Funciones

NumPy proporciona una gran cantidad de funciones predefinidas y que se pueden aplicar directamente sobre las estructuras de datos vistas anteriormente o las propias de Python (listas, matrices, etcétera). Algunas de las más utilizadas en el análisis de datos son:

In [5]:
import numpy as np

# Crear un array para el ejemplo
arr = np.array([1, 2, 3, 4, 5])

# Operaciones Aritméticas
print("Suma:", np.add(arr, 5))
print("Producto:", np.multiply(arr, 3))

# Logarítmicas y Exponenciales
print("Logaritmo natural:", np.log(arr))
print("Exponencial:", np.exp(arr))

# Funciones Estadísticas
print("Media:", np.mean(arr))
print("Mediana:", np.median(arr))
print("Desviación estándar:", np.std(arr))
print("Varianza:", np.var(arr))
print("Máximo valor:", np.max(arr))
print("Índice del máximo valor:", np.argmax(arr))
print("Mínimo valor:", np.min(arr))
print("Índice del mínimo valor:", np.argmin(arr))
print("Suma de todos los elementos:", np.sum(arr))

# Funciones de Redondeo
arr_decimal = np.array([1.23, 2.47, 3.56, 4.89])
print("Redondeo:", np.around(arr_decimal))
print("Entero menor (floor):", np.floor(arr_decimal))
print("Entero mayor (ceil):", np.ceil(arr_decimal))

Suma: [ 6  7  8  9 10]
Producto: [ 3  6  9 12 15]
Logaritmo natural: [0.         0.69314718 1.09861229 1.38629436 1.60943791]
Exponencial: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
Media: 3.0
Mediana: 3.0
Desviación estándar: 1.4142135623730951
Varianza: 2.0
Máximo valor: 5
Índice del máximo valor: 4
Mínimo valor: 1
Índice del mínimo valor: 0
Suma de todos los elementos: 15
Redondeo: [1. 2. 4. 5.]
Entero menor (floor): [1. 2. 3. 4.]
Entero mayor (ceil): [2. 3. 4. 5.]


## Ejercicios: Haz clic en "open in colab" para realizarlos

> Solución: https://github.com/4GeeksAcademy/machine-learning-prework/blob/main/02-numpy/02.1-Intro-to-Numpy_solutions.ipynb

### Creación de arrays

#### Ejercicio 01:  Crea un **vector nulo** (*null vector*) que tenga 10 elementos (★☆☆)

Un vector nulo es un array de una dimensión compuesto por ceros (`0`).

> NOTA: Revisa la función `np.zeros` (https://numpy.org/doc/stable/reference/generated/numpy.zeros.html)

In [6]:
import numpy as np
diezceros = np.zeros(10, dtype=int)
diezceros

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### Ejercicio 02: Crea un vector de unos que tenga 10 elementos (★☆☆)

> NOTA: Revisa la función `np.ones` (https://numpy.org/doc/stable/reference/generated/numpy.ones.html)

In [7]:
import numpy as np
diezunos= np.ones(10, dtype=int)
diezunos

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

#### Ejercicio 03: Investiga la función `linspace` de NumPy y crea un array que contenga 10 elementos (★☆☆)

> NOTA: Revisa la función `np.linspace` (https://numpy.org/doc/stable/reference/generated/numpy.linspace.html)

In [8]:
import numpy as np
vector10 = np.linspace(0, 9, num=10, endpoint=True, retstep=False, dtype=int, axis=0)
vector10

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### Ejercicio 04: Busca varias formas de generar un array con números aleatorios y crea un array 1D y dos arrays 2D (★★☆)

> NOTA: Revisa las funciones `np.random.rand` (https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html), `np.random.randint` (https://numpy.org/doc/stable/reference/random/generated/numpy.random.randint.html) y `np.random.randn` (https://numpy.org/doc/stable/reference/random/generated/numpy.random.randn.html)

In [9]:
import numpy as np
import random
random.seed(42)
rng1x10= np.array(np.random.randint(100,size=(10)), dtype=int)
rng1x10
rng2x10A = np.array(np.random.randint(-100,100, size=(2,10)))
rng2x10B = np.random.randint(101, 201, size=(2, 10))

#### Ejercicio 05: Crea una matriz (array 2D) identidad de 5x5 (★☆☆)


> NOTA: Revisa la función `np.eye`(https://numpy.org/devdocs/reference/generated/numpy.eye.html)

In [10]:
import numpy as np, random
random.seed(42)
arr5x5= np.eye(5, k=0, dtype=int)
arr5x5

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

#### Ejercicio 06: Crea una matriz con números aleatorios de 3x2 y calcula el valor mínimo y máximo (★☆☆)

> NOTA: Revisa la función `np.min` (https://numpy.org/devdocs/reference/generated/numpy.min.html) y `np.max` (https://numpy.org/devdocs/reference/generated/numpy.max.html)

In [11]:
arr3x2 = np.random.randint(-100,100, size=(3,2))
print(arr3x2)
minvalue = np.min(arr3x2)
maxvalue = np.max(arr3x2)
minvaluev2 = arr3x2.min()
maxvaluev2 = arr3x2.max()
print('Min', minvalue, '\n', 'Max', maxvalue, '\n')
print('Minv2', minvaluev2, '\n', 'Maxv2', maxvaluev2, '\n')



[[ 35 -28]
 [-50 -34]
 [ 90  -1]]
Min -50 
 Max 90 

Minv2 -50 
 Maxv2 90 



#### Ejercicio 07: Crea un vector con números aleatorios de 30 elementos y calcula la media (★☆☆)

> NOTA: Revisa la función `np.mean` (https://numpy.org/doc/stable/reference/generated/numpy.mean.html)

In [12]:
import numpy as np
import random
random.seed(42)
vector30 = np.random.uniform(-100, 100, size=(1, 30))
vector30

array([[-68.27295462,  87.09911378,  58.74105695, -84.41271395,
        -12.39768039,  50.97049687,  59.00359572, -87.7049059 ,
        -56.33822269, -99.84201368,  39.85578985, -61.95594   ,
         97.88635218,  -8.86740561,  86.17547618,  -0.41054231,
        -35.60680296, -69.2247191 ,  -1.89520882,   0.43065883,
         88.05828462,  21.66829708, -54.31952408, -67.34125055,
         -7.32712262, -50.23858654,  27.82676777, -72.60268786,
         40.20766531,   6.17467651]])

#### Ejercicio 08: Convierte la lista `[1, 2, 3]` y la tupla `(1, 2, 3)` en arrays (★☆☆)

In [13]:
list123 = [1,2,3]
tuple123 = (1,2,3)
print('Lista:',list123,'\n','Tupla:',tuple123)
arrlist = np.array(list123)
arrtuple = np.array(tuple123)
print('ArrayList:',arrlist,"\n","ArrayTuple:",tuple123,'\n')


Lista: [1, 2, 3] 
 Tupla: (1, 2, 3)
ArrayList: [1 2 3] 
 ArrayTuple: (1, 2, 3) 



### Operaciones entre arrays

#### Ejercicio 09: Invierte el vector del ejercicio anterior (★☆☆)

> NOTA: Revisa la función `np.flip` (https://numpy.org/doc/stable/reference/generated/numpy.flip.html)

In [14]:
import numpy as np, random

ArrInvList = np.flip(arrlist),
ArrInvTuple = np.flip(arrtuple),
print(ArrInvList,'\n',ArrInvTuple)

(array([3, 2, 1]),) 
 (array([3, 2, 1]),)


#### Ejercicio 10: Cambia el tamaño de un array aleatorio de dimensiones 5x12 en 12x5 (★☆☆)

> NOTA: Revisa la función `np.reshape` (https://numpy.org/doc/stable/reference/generated/numpy.reshape.html)

In [15]:
import numpy as np
import random
random.seed(42)
Matriz5x12 = np.random.uniform(-100, 100, size=(5, 12))
Matriz12x5 = np.reshape(Matriz5x12, (12,5))
print("Matriz5x12:",Matriz5x12,"\n","Matriz12x5:",Matriz12x5,"\n")

Matriz5x12: [[  4.24853123  34.32794038 -75.74481643 -46.77500416 -16.786262
   16.73508839   4.15448722 -61.52373638  24.78164934 -60.77576832
   82.53950749 -35.98981253]
 [-98.53147461 -80.16526086 -44.47654956   3.44656353  23.36817033
   -3.36475867 -82.92232094  -8.38088798  25.3329711  -95.21472204
   78.52214758  88.16184712]
 [ 63.70002948 -44.95070112   4.28400743 -52.73722414  20.40474928
   28.06444518 -27.38285514 -58.92028285 -99.0721412   -1.37353202
   35.91233572  56.32941367]
 [ 49.1071575  -84.28728102 -19.26595435   9.03243676 -89.34036769
   92.47246091 -65.04871468 -49.77152323 -81.84348249  98.40515319
   -0.14269419  52.92655853]
 [-73.29242595 -78.19658294 -11.64151843  28.34221275 -38.50104238
   74.7714484    4.31291031 -26.54698793 -44.82047322  92.15682257
    3.035697   -22.93802416]] 
 Matriz12x5: [[  4.24853123  34.32794038 -75.74481643 -46.77500416 -16.786262  ]
 [ 16.73508839   4.15448722 -61.52373638  24.78164934 -60.77576832]
 [ 82.53950749 -35.98981

#### Ejercicio 11: Convierte la lista `[1, 2, 0, 0, 4, 0]` en un array y obtén el índice de los elementos que no son cero (★★☆)

> NOTA: Revisa la función `np.where` (https://numpy.org/devdocs/reference/generated/numpy.where.html)

In [16]:
import numpy as np
import random
random.seed(42)
list1=[1,2,0,0,4,0]
listarr1= np.array(list1)
listsin0 = np.where(listarr1!=0)
listsin0

(array([0, 1, 4]),)

#### Ejercicio 12: Convierte la lista `[0, 5, -1, 3, 15]` en un array, multiplica sus valores por `-2` y obtén los elementos pares (★★☆)
list12 = [0,5,-1,3,15]
array12 = np.array(list12)
for array12 i in range (5)
    array12.index(i).value(*2)
    return np.where(array12.value)

In [17]:
import numpy as np

list12 = [0, 5, -1, 3, 15]
array12 = np.array(list12)
array12 *= -2
for i in range(len(array12)):
    if array12[i] % 2 == 0:
        print(f"El elemento en el índice {i} es par: {array12[i]}")

El elemento en el índice 0 es par: 0
El elemento en el índice 1 es par: -10
El elemento en el índice 2 es par: 2
El elemento en el índice 3 es par: -6
El elemento en el índice 4 es par: -30

El elemento en el índice 1 es par: -10
El elemento en el índice 2 es par: 2
El elemento en el índice 3 es par: -6
El elemento en el índice 4 es par: -30


#### Ejercicio 13: Crea un vector aleatorio de 10 elementos y ordénalo de menor a mayor (★★☆)

> NOTA: Revisa la función `np.sort` (https://numpy.org/doc/stable/reference/generated/numpy.sort.html)

In [22]:
import numpy as np, random
random.seed(42)

array13 = np.array(np.random.uniform(-100, 100, size=(1,10)))
sorted13 = np.sort(array13)
print("SinOrden:",array13,"\n","Ordenado:",sorted13,"\n")

SinOrden: [[ 56.15718149 -56.16362462 -38.32743542  29.25979067   8.12953839
   78.15159525  57.46227699  70.21005171 -30.96005539 -76.71192987]] 
 Ordenado: [[-76.71192987 -56.16362462 -38.32743542 -30.96005539   8.12953839
   29.25979067  56.15718149  57.46227699  70.21005171  78.15159525]] 



#### Ejercicio 14: Genera dos vectores aleatorios de 8 elementos y aplica las operaciones de suma, resta y multiplicación entre ellos (★★☆)

> NOTA: Revisa las funciones matemáticas: https://numpy.org/doc/stable/reference/routines.math.html

In [28]:
import numpy as np, random
random.seed(42)

array13 = np.array(np.random.randint(-100, 100, size=(1,10)))
sorted13 = np.sort(array13)
print("SinOrden:",array13,"\n","Ordenado:",sorted13,"\n")

SinOrden: [[ 83  -7  81  -6 -23  47  61  56 -29  50]] 
 Ordenado: [[-29 -23  -7  -6  47  50  56  61  81  83]] 



#### Ejercicio 15: Convierte la lista `[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]` en un array y transfórmalo en una matriz con filas de 3 columnas (★★★)

In [30]:
lista15=[1,2,3,4,5,6,7,8,9,10,11,12]
array15= np.array(lista15)
array4x315 = np.reshape(array15, shape=(4,3))
array4x315

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])